<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ECommerceManagement.Domain\ECommerceManagement.Domain.csproj" />
      <ProjectReference Include="..\..\src\ECommerceManagement.Repository\ECommerceManagement.Repository.csproj" />
    </ItemGroup>

</Project>
