<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ECommerceManagement.Domain\ECommerceManagement.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.2.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.10" />
      <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Validations\" />
    </ItemGroup>

</Project>
